import app1 from "./demo-app (1).webp";
import app2 from "./demo-app (2).webp";
import app3 from "./demo-app (3).webp";
import app4 from "./demo-app (4).webp";
import app5 from "./demo-app (5).webp";
import app6 from "./demo-app (6).webp";

const appData = [
  { id: 1, image: app1, title: "SnapPic", companyName: "Pixel Labs", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 45, reviews: 12500, downloads: 5, ratingAvg: 4.5, ratings: [ { name: "1 star", count: 500 }, { name: "2 star", count: 700 }, { name: "3 star", count: 1200 }, { name: "4 star", count: 3 }, { name: "5 star", count: 7300 } ] },
  { id: 2, image: app2, title: "TaskTracker", companyName: "Productive Inc.", description: "This is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 38, reviews: 8500, downloads: 2, ratingAvg: 4.3, ratings: [ { name: "1 star", count: 400 }, { name: "2 star", count: 600 }, { name: "3 star", count: 1200 }, { name: "4 star", count: 2400 }, { name: "5 star", count: 3900 } ] },
  { id: 3, image: app3, title: "FitTrack", companyName: "HealthZone", description: "This is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 52, reviews: 43200, downloads: 10, ratingAvg: 4.7, ratings: [ { name: "1 star", count: 900 }, { name: "2 star", count: 1200 }, { name: "3 star", count: 2200 }, { name: "4 star", count: 7800 }, { name: "5 star", count: 31200 } ] },
  { id: 4, image: app4, title: "NewsNow", companyName: "DailyByte Media", description: "This is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 28, reviews: 15400, downloads: 4, ratingAvg: 4.1, ratings: [ { name: "1 star", count: 1000 }, { name: "2 star", count: 1200 }, { name: "3 star", count: 3000 }, { name: "4 star", count: 4800 }, { name: "5 star", count: 5400 } ] },
  { id: 5, image: app5, title: "MusicBox", companyName: "TuneWave", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 80, reviews: 72000, downloads: 50, ratingAvg: 4.6, ratings: [ { name: "1 star", count: 3500 }, { name: "2 star", count: 4000 }, { name: "3 star", count: 7000 }, { name: "4 star", count: 15000 }, { name: "5 star", count: 44500 } ] },
  { id: 6, image: app6, title: "TravelMate", companyName: "ExploreMore Ltd.", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 61, reviews: 19200, downloads: 6, ratingAvg: 4.4, ratings: [ { name: "1 star", count: 800 }, { name: "2 star", count: 1200 }, { name: "3 star", count: 2500 }, { name: "4 star", count: 5600 }, { name: "5 star", count: 9100 } ] },
  { id: 7, image: app1, title: "NotePro", companyName: "SoftCraft", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 30, reviews: 10400, downloads: 2.5, ratingAvg: 4.2, ratings: [ { name: "1 star", count: 600 }, { name: "2 star", count: 800 }, { name: "3 star", count: 1500 }, { name: "4 star", count: 3600 }, { name: "5 star", count: 3900 } ] },
  { id: 8, image: app2, title: "ShopEasy", companyName: "BuySmart", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 75, reviews: 56200, downloads: 30, ratingAvg: 4.3, ratings: [ { name: "1 star", count: 3200 }, { name: "2 star", count: 3800 }, { name: "3 star", count: 6000 }, { name: "4 star", count: 12000 }, { name: "5 star", count: 31200 } ] },
  { id: 9, image: app3, title: "ChatLine", companyName: "NextWave", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 50, reviews: 82000, downloads: 70, ratingAvg: 4.6, ratings: [ { name: "1 star", count: 4100 }, { name: "2 star", count: 5000 }, { name: "3 star", count: 9200 }, { name: "4 star", count: 17000 }, { name: "5 star", count: 47100 } ] },
  { id: 10, image: app4, title: "EduLearn", companyName: "MindSpark", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 68, reviews: 29000, downloads: 12, ratingAvg: 4.8, ratings: [ { name: "1 star", count: 500 }, { name: "2 star", count: 700 }, { name: "3 star", count: 1400 }, { name: "4 star", count: 3800 }, { name: "5 star", count: 22400 } ] },
  { id: 11, image: app5, title: "BudgetBuddy", companyName: "FinTrack Co.", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 35, reviews: 9800, downloads: 1.5, ratingAvg: 4.4, ratings: [ { name: "1 star", count: 400 }, { name: "2 star", count: 600 }, { name: "3 star", count: 1200 }, { name: "4 star", count: 3200 }, { name: "5 star", count: 4400 } ] },
  { id: 12, image: app6, title: "WeatherWise", companyName: "SkyNet Systems", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 42, reviews: 23000, downloads: 9, ratingAvg: 4.5, ratings: [ { name: "1 star", count: 900 }, { name: "2 star", count: 1200 }, { name: "3 star", count: 2100 }, { name: "4 star", count: 6400 }, { name: "5 star", count: 12400 } ] },
  { id: 13, image: app1, title: "PhotoBlend", companyName: "Pixel Labs", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 50, reviews: 15000, downloads: 6, ratingAvg: 4.3, ratings: [ { name: "1 star", count: 400 }, { name: "2 star", count: 600 }, { name: "3 star", count: 1200 }, { name: "4 star", count: 3500 }, { name: "5 star", count: 8300 } ] },
  { id: 14, image: app2, title: "FocusTask", companyName: "Productive Inc.", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 40, reviews: 9000, downloads: 2, ratingAvg: 4.1, ratings: [ { name: "1 star", count: 300 }, { name: "2 star", count: 500 }, { name: "3 star", count: 900 }, { name: "4 star", count: 1800 }, { name: "5 star", count: 5400 } ] },
  { id: 15, image: app3, title: "HealthMate", companyName: "HealthZone", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 55, reviews: 46000, downloads: 11, ratingAvg: 4.7, ratings: [ { name: "1 star", count: 1000 }, { name: "2 star", count: 1800 }, { name: "3 star", count: 4000 }, { name: "4 star", count: 10000 }, { name: "5 star", count: 27800 } ] },
  { id: 16, image: app4, title: "DailyNews", companyName: "DailyByte Media", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 30, reviews: 16000, downloads: 4.5, ratingAvg: 4.4, ratings: [ { name: "1 star", count: 400 }, { name: "2 star", count: 700 }, { name: "3 star", count: 1500 }, { name: "4 star", count: 4500 }, { name: "5 star", count: 9100 } ] },
  { id: 17, image: app5, title: "TuneStream", companyName: "TuneWave", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 85, reviews: 75000, downloads: 52, ratingAvg: 4.6, ratings: [ { name: "1 star", count: 1200 }, { name: "2 star", count: 1800 }, { name: "3 star", count: 4000 }, { name: "4 star", count: 18000 }, { name: "5 star", count: 49500 } ] },
  { id: 18, image: app6, title: "TripPlanner", companyName: "ExploreMore Ltd.", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 65, reviews: 20000, downloads: 6.5, ratingAvg: 4.4, ratings: [ { name: "1 star", count: 400 }, { name: "2 star", count: 800 }, { name: "3 star", count: 1800 }, { name: "4 star", count: 5000 }, { name: "5 star", count: 11800 } ] },
  { id: 19, image: app1, title: "MemoPad", companyName: "SoftCraft", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 32, reviews: 11000, downloads: 2.7, ratingAvg: 4.2, ratings: [ { name: "1 star", count: 300 }, { name: "2 star", count: 500 }, { name: "3 star", count: 1000 }, { name: "4 star", count: 2200 }, { name: "5 star", count: 7100 } ] },
  { id: 20, image: app2, title: "EasyShop", companyName: "BuySmart", description: "This app is a cutting-edge AI-powered photo editing application designed for both amateur photographers and professional creatives. The app leverages advanced machine learning algorithms to automatically analyze photos and enhance them in a matter of seconds. Users can adjust bright.", size: 78, reviews: 58000, downloads: 31, ratingAvg: 4.3, ratings: [ { name: "1 star", count: 700 }, { name: "2 star", count: 900 }, { name: "3 star", count: 2500 }, { name: "4 star", count: 8000 }, { name: "5 star", count: 46000 } ] }
];

export default appData;